<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class LabelTest extends TestCase
{
    use RefreshDatabase;

    public function setup(): void
    {
        parent::setup(); // TODO: Change the autogenerated stub
        $this->authUser();
    }

    /**
     * @test
     */
    public function user_can_create_new_label()
    {
        $this->postJson
        (
            route("api.labels.store"),
            ["title" => "My label", "colour" => "red"]
        )
             ->assertCreated();

        $this->assertDatabaseHas(
            "labels",
            [
                "title" => "My label",
                "colour" => "red",
            ]
        );
    }
}
