<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ServiceTest extends TestCase
{
    use RefreshDatabase;

    public function setup(): void
    {
        parent::setup(); // TODO: Change the autogenerated stub
        $this->authUser();
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_user_can_connect_to_service_and_token_is_stored()
    {
        $response = $this->getJson(route("api.google.service.connect", "google-drive"))
                         ->assertOk();

        $this->assertArrayHasKey("authenticate_redirect_url", $response->json());
    }
}
