<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ServiceTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @var \Illuminate\Database\Eloquent\Collection|\Illuminate\Database\Eloquent\Model
     */
    private $user;

    public function setup(): void
    {
        parent::setup(); // TODO: Change the autogenerated stub
        $this->user = $this->authUser();
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_user_can_connect_to_service_and_authenticate_redirect_url_is_returned()
    {
        $response = $this->getJson(route("api.google.service.connect", "google-drive"))
                         ->assertOk();

        $this->assertArrayHasKey("authenticate_redirect_url", $response->json());
    }

    public function test_service_callback_will_store_token()
    {
        $response = $this->postJson(route("api.google.service.callback", ["code" => "dummy-code"]))
                         ->assertCreated();

        //token field in db as json
        $this->assertDatabaseHas("web_services", ["user_id" => $this->user->id]);
//        $this->assertNotNull($this->user->services->first()->token);

    }
}
